# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-16 02:28
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='alerts',
            fields=[
                ('alert_id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='blog_post',
            fields=[
                ('blog_post_id', models.AutoField(primary_key=True, serialize=False)),
                ('author', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='image',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_image', models.BinaryField()),
                ('zip', models.IntegerField()),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('is_storm_spotter', models.BooleanField(default=False)),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='tags',
            fields=[
                ('tag_id', models.AutoField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='user_alerts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.alerts')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='response_post',
            fields=[
                ('blog_post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blog_post')),
            ],
            bases=('blog.blog_post',),
        ),
        migrations.CreateModel(
            name='top_post',
            fields=[
                ('blog_post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.blog_post')),
                ('title', models.CharField(max_length=100)),
            ],
            bases=('blog.blog_post',),
        ),
        migrations.AddField(
            model_name='tags',
            name='blog_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_post'),
        ),
        migrations.AddField(
            model_name='image',
            name='blog_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blog_post'),
        ),
        migrations.AddField(
            model_name='blog_post',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='response_post',
            name='top_post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.top_post'),
        ),
    ]
