# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-17 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180315_2128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_id',
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
