# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-03-22 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20180320_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='blogImages/%Y/%m/%d'),
        ),
    ]
