# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20180326_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_storm_spotter',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=None, max_digits=9),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, upload_to='profileImages/%Y/%m/%d/%H/%M/%S/%f'),
        ),
    ]
