# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-04-01 22:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20180331_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(max_length=500),
        ),
    ]
